<?php include "header.phtml" ?>
<?php
/**
 * @var string|null $name
 */
?>

    <div id="top">
        <?php if (!$name) { ?>
            <?php include "login.form.phtml" ?>
        <?php } else { ?>
            Привет, <?= $name ?>! <a id="logout" href="#">logout</a>
            <div>
                <a href="/admin">Редактировать дерево?</a>
            </div>
        <?php } ?>
    </div>

    <div class="row">

        <div id="tree" class="float-left">
        </div>

        <div id="editor" data-edit="no" class="float-left">
            <h3 id="name"></h3>
            <p id="content"></p>
        </div>

    </div>

<?php include "footer.phtml" ?>